/var/log/nginx/osmap.public.access.log root:wheel 640 14 50000 * Z /var/run/nginx.pid "kill -USR1 $(cat /var/run/nginx.pid) >/dev/null 2>&1 || true"
/var/log/nginx/osmap.public.error.log  root:wheel 640 14 20000 * Z /var/run/nginx.pid "kill -USR1 $(cat /var/run/nginx.pid) >/dev/null 2>&1 || true"
/var/log/nginx/osmap.differential.access.log root:wheel 640 14 20000 * Z /var/run/nginx.pid "kill -USR1 $(cat /var/run/nginx.pid) >/dev/null 2>&1 || true"
