//! PAGE19 settings, separate from the public inventory inspector.
use super::*;
pub(crate) fn render_openpgp_settings(
    account: &str,
    csrf: &str,
    inventory: &crate::http_ui::key_inventory_ui::PublicInventoryView,
) -> TrustedHtml {
    use crate::http_ui::key_inventory_ui::PublicInventoryView;
    let status=match inventory {PublicInventoryView::Verified{account:owner,keys} if owner==account=>format!("<strong>Public inventory verified</strong><span>{} public {} reported. Private-key readiness is unavailable.</span>",keys.len(), if keys.len() == 1 { "key" } else { "keys" }),_=>"<strong>Public inventory unavailable</strong><span>Account capability could not be established.</span>".into()};
    let policies=[("Full fingerprint binding","Account and recipient bindings are unavailable."),("Missing recipient key","Protected-delivery policy is unavailable."),("Automatic key discovery","Discovery policy has not been qualified."),("Private-key handling","Private-key capability is unavailable.")].into_iter().map(|(label,help)|format!("<li><div><strong>{label}</strong><span>{help}</span></div><span class=\"openpgp-policy-state\">Unavailable</span></li>")).collect::<String>();
    TrustedHtml::from_template(format!(concat!("{header}<main id=\"main-content\" class=\"page-shell settings-page openpgp-settings-page\" tabindex=\"-1\"><div class=\"page-intro\"><h1>Settings</h1><p>Inspect public inventory and account protection capabilities.</p></div><div class=\"settings-layout\">{nav}<div class=\"openpgp-settings-grid\"><section class=\"openpgp-settings-card\"><h2>Account Capability</h2><div class=\"openpgp-account-status\">{status}</div><div class=\"openpgp-setting-row\"><label for=\"account-key\">Key fingerprint</label><input id=\"account-key\" readonly value=\"Account binding unavailable\"></div><div class=\"openpgp-setting-row\"><label for=\"signing-setting\">Signing</label><select id=\"signing-setting\" disabled><option>Unavailable</option></select></div><div class=\"openpgp-setting-row\"><label for=\"encryption-setting\">Encryption</label><select id=\"encryption-setting\" disabled><option>Unavailable</option></select></div><div class=\"openpgp-setting-row\"><label for=\"self-setting\">Encrypt to self</label><select id=\"self-setting\" disabled><option>Unavailable</option></select></div><a class=\"button-link openpgp-manage\" href=\"/settings/keys\">Manage Keys</a></section><section class=\"openpgp-settings-card\"><h2>Policy Behavior</h2><ul class=\"openpgp-policy-list\">{policies}</ul></section></div></div></main>"),header=app_header(account,csrf,"settings-openpgp"),nav=settings_navigation("openpgp"),status=status,policies=policies))
}
